### ISSUE TITLE
`npm install` for `"^2.6.1"` fails

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/cdc-open-viz#100]
**Steps:**
1. Create a new, clean directory.
2. `cd` into directory
3. Create a minimal package.json
  (e.g. this can be done with `node init` or use the package.json below.
4. Add ` "dependencies": {  "@cdc/map": "2.6.1"  }` to file

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@cdc/map": "^2.6.1"
  }
}
```
5. Run `npm install` in this directory.
6. Observe contents of `node_module/@cdc/map` directory. 
 (e.g. `ls -lasR ./node_modules/@cdc/map`)

**Result:** 
Directory contains only 3 files: `LICENSE`, `README.md` and `package.json`

**Notes:** 
- changing to 2.5 works as expected 
  (e.g.`"dependencies": {"@cdc/map": "2.5.0" }`)
- My `npm --version` `6.14.13`
- My `node --version` `v14.17.0`

**Comment by danielimmke** [comment]
This was a good catch, thank you! I have published new versions of these packages to NPM. So 2.6.2 will have the files you need.

**Comment by TomNUSDS** [comment]
Thanks for the quick turn-around! Love the project.
