### ISSUE TITLE
[WCMSRD-12782] React warns of memory leak when unloading usa cdcmap

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/cdc-open-viz#112]
We're getting console warnings when our unit tests run that is coming from the cdcmap component when it unloads.

To produce:
```javascript
const [showMap, setShowMap] = useState(false);
import mapdata from "./mapdata.json";

return (<>
<div>
  <label>Show map
  <input
    type="checkbox"
    checked={showMap}
    onChange={() => setShowMap((prev) => !prev)}
  />
  </label>
</div>

<div>{showMap ? <CdcMap config={mapdata} /> : null}</div>
</>);
```
 - toggle the map on and back off while watching the debugger console.
 
You can also try it out here:
 https://codesandbox.io/s/demo-cdc-map-unmount-leak-rbv0h?file=/src/App.js
 
Error:
 > Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at LC (/node_modules/@cdc/map/dist/cdcmap.js:1:716965)

**Comment by TomNUSDS** [comment]
You might start by double-checking out this code from `UsaMap.js`

```javascript
  useEffect(() => {
    // Territories need to show up if they're in the data at all, not just if they're "active". That's why this is different from Cities
    const territoriesList = territoriesKeys.filter(key => data[key]);

    setTerritoriesData(territoriesList);
  }, [data]);
```

I _think_ it needs to return a `cleanup` function that calls `setTerritoriesData([])`?  
But I haven't dug too deeply, so that may not be right.

**Comment by adamdoe** [comment]
@rshelnutt @TomNUSDS - after adding the cleanup function referenced above I'm no longer getting the error. Once we get this tested and released to npm I'll update the issue.
