### ISSUE TITLE
Labels are always rendered

### ISSUE THREAD

**Issue by jayb** [CDCgov/cdc-open-viz#1441]
Labels are [rendered](https://github.com/CDCgov/cdc-open-viz/blob/main/packages/chart/src/components/LineChart/index.tsx#L100-L102) with `display:none` on charts that have labels turned off. This can be quite slow on some charts (e.g. line charts with many values) and adds uneccessary DOM complexity.

It seems better to suppress the labels entirely, unless they're needed for something else that I haven't noticed.

I have the code for this on a branch locally but am unable to push. cc @adamdoe

**Comment by adamdoe** [comment]
Discussed offline and directed to [Contributing Guidelines](https://github.com/CDCgov/cdc-open-viz/blob/main/CONTRIBUTING.md)
