### ISSUE TITLE
Create dev-zfi4 branch request + Minor changes to get to build 

### ISSUE THREAD

**Issue by jcbowyer** [CDCgov/cdc-open-viz#562]
I am working on creating some visuals for EDO office at CDC.  

Request 1:

* Please create a branch dev-zfi4 or grant user jcbowyer permission to create branch dev-zfi4 and publish

Request 2: 

Review notes below.

When doing a pull request and following these steps on Ubuntu, I ran into a couple of issues:

* Start by cloning this repo and running yarn install at the root.
*  Run lerna bootstrap and Lerna will initialize all the packages for you.
* Run lerna run build to build all of the packages in the correct order.
* To begin working on an individual package, run lerna run --scope @cdc/package_name start, replacing package_name with the package's name (ex: @cdc/map).

Changes required in package.json in devDependencies

 * changed "react": "17.0.1" to "react": "17.0.2"
 * changed "react-dom": "17.0.1" to "17.0.2

Changes required in package.json in dependencies

* changed  "@cdc/core": "^1.1.2" to "@cdc/core": "^4.23.1"

**Comment by adamdoe** [comment]
@jcbowyer - discussed internally. If there's any additional input needed please re-open.
