### ISSUE TITLE
@cdc/core 4.23.9 doesn't exist

### ISSUE THREAD

**Issue by k88hudson-cfa** [CDCgov/cdc-open-viz#871]
In a clean directory, run `npm install @cdc/editor@4.23.9`. This results in the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @cdc/core@^4.23.9.
```

Running `npm info @cdc/core`, it looks like `4.23.8` is the latest published version

**Comment by adamdoe** [comment]
Hi @k88hudson-cfa - sorry for the delayed response here. It looks like our last push to npm must have failed on core. I've updated the core package to 4.23.9. Let me know if that helps.

**Comment by k88hudson-cfa** [comment]
Awesome! All good now 👍
